version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      # setup
      - dt=$(date '+%Y%m%d%H%M%S');
      - project_name=leet
  build:
    commands:
      # service 11/4
      - cd $CODEBUILD_SRC_DIR/dsa-python
      - pip install -r requirements.txt
      - pytest -v -s --html-report=./report
      - aws s3 cp pytest_html_report.html s3://leet.brandonv.io
      - aws s3 cp output.json s3://leet.brandonv.io
