version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      # setup
      - dt=$(date '+%Y%m%d%H%M%S');
      - project_name=leet
  build:
    commands:
      # service
      - cd $CODEBUILD_SRC_DIR/dsa-pythong
      - pip install requirements
      - pytest
